name: Daily Strava Members Sync

on:
  workflow_dispatch: # Permite que a Supabase clique no "botão" via API

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Members Sync Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          STRAVA_CLUB_ID: ${{ secrets.STRAVA_CLUB_ID }}
          # ... adiciona aqui os teve secrets do Strava se o script precisar deles
        run: python sync_members.py
